### ISSUE TITLE
Any news regarding android?

### ISSUE THREAD

**Issue by Murii** [Tangent128/luasdl2#23]
Hello! A while ago I asked the same question regarding android.Do you got any news? Can we access opengl and opengl es?

**Comment by Tangent128** [comment]
The current status, unfortunately, is simply "the code itself should be work with Android, since it only depends on Lua and SDL2 which both in turn support Android, but the current build system has no way to target Android so you'll have to set up the project yourself."

I am not in a position to change that right now; however, I will happily accept patches that add that support.

**Comment by Murii** [comment]
Okay,glad to hear that! I have one more question.After making all the .so how do I start the examples with sublime text? I'm not use to work with .so files and lua

**Comment by Murii** [comment]
Also an IRC channel on freenode would be nice!

**Comment by Murii** [comment]
How can I distribute my game?

**Comment by Tangent128** [comment]
If you are referring to distribution *on Android*, I can't help there. You'd need to ask an Android forum.

If you mean just distributing to *desktop systems* via a zip file, then you would need to bundle:
* the Lua interpreter + any dependencies for the platform in question (depends how Lua was built, a static Lua build is only one file, Windows typically has lua.exe and lua.dll together)
* your Lua script files
* the Lua-SDL2 module(s)
* a wrapper script that sets LUA_PATH and LUA_CPATH (and if necessary LD_LIBRARY_PATH) to the right paths and launches Lua with your script

[srlua](https://github.com/LuaDist/srlua) might be able to help, but I haven't used it.
