### ISSUE TITLE
Quick Question!

### ISSUE THREAD

**Issue by Murii** [Tangent128/luasdl2#4]
Hello does luasdl 2 work with android? I mean can I compile it to android and make it work?Also does it work on all desktop platforms? Thanks!

Edit 1 : It works with 2d and 3d right?

**Comment by Murii** [comment]
Also how can I compile the .lua examples?

**Comment by Tangent128** [comment]
Lua is a scripting language, not a compiled language, so the .lua examples should work by running "lua path/to/script" so long as you have luasdl2 installed where the interpreter can find it.

As for the main question, I do not know either way as to whether compiling for Android works or not. 

SDL2 is supposed to work with Android, and luasdl2 tries to bind only to SDL2's APIs and not anything platform-specific, so in theory it should at least be possible. The build system's where you are probably most likely to stumble.

So, short answer, you can probably "make it work", but it might be a fight.

Desktop-wise, the code should support Linux, Windows, and OS X just fine. (I am not equipped to test the latter two at the moment, but since taking over maintainership I have not made any changes that should break them and nobody has reported them broken.)

Also probably of relevance to you, SDL2's drawing functions are supported, including initializing an OpenGL context, but as SDL does not wrap the OpenGL functions, you'll need a separate OpenGL binding if you want to draw 3D graphics.

**Comment by Murii** [comment]
I'm a linux user too.Any programs recomanded for building everything?

**Comment by Tangent128** [comment]
cmake is the build system used; find an IDE suiting your tastes, or else use the command line.

You'll also need Lua, obviously.
