### ISSUE TITLE
Question. Using Release without Luarocks

### ISSUE THREAD

**Issue by dmoa** [Tangent128/luasdl2#84]
When downloading the release, is there any way I can use it "fresh out the box" without luarocks?

Cheers.

**Comment by Tangent128** [comment]
It's been a while since I've done maintenance on this, but the Cmake build should still work; see https://github.com/Tangent128/luasdl2/blob/master/INSTALL.md

If neither luarocks nor cmake are an option, there aren't any other automated options included, but if you want to roll a makefile or build script you can find the lists of source files for each module in https://github.com/Tangent128/luasdl2/blob/master/lua-sdl2-scm-3.rockspec (note the PlusCommon helper that adds some common files to each module)

**Comment by markand** [comment]
There are no prebuilt binaries because it's too complicated to generate especially given the numerous platforms there are and Lua version there are. Using the CMake or luarocks spec to build is quite easy though.
